//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinGallery.Services.Utils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Credentials {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Credentials() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinGallery.Services.Utils.Credentials", typeof(Credentials).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yuletodim.apps@gmail.com.
        /// </summary>
        public static string AppEmail {
            get {
                return ResourceManager.GetString("AppEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123qwe@#.
        /// </summary>
        public static string EmailPass {
            get {
                return ResourceManager.GetString("EmailPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2097138040512814.
        /// </summary>
        public static string FacebookAppID {
            get {
                return ResourceManager.GetString("FacebookAppID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 863102e170b30b73a685d195e79b2ccf.
        /// </summary>
        public static string FacebookAppSecret {
            get {
                return ResourceManager.GetString("FacebookAppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 341679455982-bkl6050k3s5t6f7nmdpgus8rum1jc4ic.apps.googleusercontent.com.
        /// </summary>
        public static string GoogleClientID {
            get {
                return ResourceManager.GetString("GoogleClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lZyP0kGqr4yer_wDyRhV-AfA.
        /// </summary>
        public static string GoogleClientSecret {
            get {
                return ResourceManager.GetString("GoogleClientSecret", resourceCulture);
            }
        }
    }
}
